=== riyash0109/xml_lab_test1/flight.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="Travel">        
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Flight" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="flightNo" type="xs:integer"/>
							<xs:element name="airlineName" type="xs:string"/>
							<xs:element name="source" type="xs:string"/>
							<xs:element name="destination" type="xs:string"/> 
							<xs:element name="fare" type="flightAmt"/>
							<xs:element name="noofseats" type="flightSeats"/>
						</xs:sequence>
                    </xs:complexType>
                </xs:element>
             </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="flightAmt">
    	<xs:restriction base="xs:integer">
    	<xs:minInclusive value="1000"/>
    	<xs:maxExclusive value="15000"/>
    </xs:restriction>
</xs:simpleType>
<xs:simpleType name="flightSeats">
    	<xs:restriction base="xs:integer">
    	<xs:minInclusive value="01"/>
    	<xs:maxExclusive value="100"/>
    </xs:restriction>
</xs:simpleType>

</xs:schema>

=== riyash0109/xml_lab_test1/flight.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="flight.xsl"?>
<Travel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="flight.xsd">

   <Flight>
    <flightNo>1234</flightNo>
    <airlineName>AirIndia</airlineName>
    <source>BLR</source>
    <destination>AMD</destination>
    <fare>4900</fare>
    <noofseats>32</noofseats>
   </Flight>

   <Flight>
    <flightNo>2345</flightNo>
    <airlineName>GoAir</airlineName>
    <source>BLR</source>
    <destination>BOM</destination>
    <fare>5200</fare>
    <noofseats>45</noofseats>
   </Flight>

   <Flight>
    <flightNo>3456</flightNo>
    <airlineName>Indigo</airlineName>
    <source>CAL</source>
    <destination>DEL</destination>
    <fare>3900</fare>
    <noofseats>57</noofseats>
   </Flight>

   <Flight>
    <flightNo>4567</flightNo>
    <airlineName>Vistara</airlineName>
    <source>DEL</source>
    <destination>HYD</destination>
    <fare>4800</fare>
    <noofseats>02</noofseats>
   </Flight>

   <Flight>
    <flightNo>5678</flightNo>
    <airlineName>AirAsia</airlineName>
    <source>HYD</source>
    <destination>MOH</destination>
    <fare>7300</fare>
    <noofseats>37</noofseats>
   </Flight>

   <Flight>
    <flightNo>6789</flightNo>
    <airlineName>SpiceJet</airlineName>
    <source>IXR</source>
    <destination>DEL</destination>
    <fare>3500</fare>
    <noofseats>17</noofseats>
   </Flight>

   <Flight>
    <flightNo>7890</flightNo>
    <airlineName>Vistara</airlineName>
    <source>DEL</source>
    <destination>AMD</destination>
    <fare>3000</fare>
    <noofseats>27</noofseats>
   </Flight>

   <Flight>
    <flightNo>8901</flightNo>
    <airlineName>AirIndia</airlineName>
    <source>AMD</source>
    <destination>CAL</destination>
    <fare>4700</fare>
    <noofseats>33</noofseats>
   </Flight>

</Travel>
